/*
MIT License

Copyright (c) 2023 Cesario Jahrim Gabriele, Kentpayeva Madina

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
package io.github.jahrim.chess.game.service.components.events

/**
 * An [[Event]] generated by the chess game service.
 *
 * <br/>
 * The [[Event]]s generated by the chess game service are organized
 * hierarchically with [[ChessGameServiceEvent]] as the root of the
 * hierarchy, as shown below:
 *
 * [[ChessGameServiceEvent]]
 *   - [[LoggingEvent]]
 *   - [[ServerStateUpdateEvent]]
 *     - [[GameStateUpdateEvent]]
 *       - [[ChessboardUpdateEvent]]
 *       - [[GameOverUpdateEvent]]
 *       - [[GameSituationUpdateEvent]]
 *       - [[MoveHistoryUpdateEvent]]
 *       - [[PlayerUpdateEvent]]
 *         - [[WhitePlayerUpdateEvent]]
 *         - [[BlackPlayerUpdateEvent]]
 *       - [[TimerUpdateEvent]]
 *         - [[WhiteTimerUpdateEvent]]
 *         - [[BlackTimerUpdateEvent]]
 *       - [[TurnUpdateEvent]]
 *     - [[ServerErrorUpdateEvent]]
 *     - [[ServerSituationUpdateEvent]]
 *     - [[SubscriptionUpdateEvent]]
 *
 * <br/>
 * By subscribing to a specific type of [[ChessGameServiceEvent]],
 * a user can observe all the events that are sub-type or same-type
 * of that type. In particular, by subscribing to the
 * [[ChessGameServiceEvent]] type, a user can observe all the events
 * of the chess game service.
 */
class ChessGameServiceEvent extends Event
