package io.github.jahrim.chess.game.service.components.events

/**
 * An [[Event]] generated by the chess game service.
 *
 * <br/>
 * The [[Event]]s generated by the chess game service are organized
 * hierarchically with [[ChessGameServiceEvent]] as the root of the
 * hierarchy, as shown below:
 *
 * [[ChessGameServiceEvent]]
 *   - [[LoggingEvent]]
 *   - [[ServerStateUpdateEvent]]
 *     - [[GameStateUpdateEvent]]
 *       - [[ChessboardUpdateEvent]]
 *       - [[GameOverUpdateEvent]]
 *       - [[GameSituationUpdateEvent]]
 *       - [[MoveHistoryUpdateEvent]]
 *       - [[PlayerUpdateEvent]]
 *         - [[WhitePlayerUpdateEvent]]
 *         - [[BlackPlayerUpdateEvent]]
 *       - [[TimerUpdateEvent]]
 *         - [[WhiteTimerUpdateEvent]]
 *         - [[BlackTimerUpdateEvent]]
 *       - [[TurnUpdateEvent]]
 *     - [[ServerErrorUpdateEvent]]
 *     - [[ServerSituationUpdateEvent]]
 *     - [[SubscriptionUpdateEvent]]
 *
 * <br/>
 * By subscribing to a specific type of [[ChessGameServiceEvent]],
 * a user can observe all the events that are sub-type or same-type
 * of that type. In particular, by subscribing to the
 * [[ChessGameServiceEvent]] type, a user can observe all the events
 * of the chess game service.
 */
class ChessGameServiceEvent extends Event
